# Site settings
title: HTS file format specifications
description: >
  <a href="/">Samtools organisation</a> for next-generation sequencing
  developers: htslib C&nbsp;API, htsjdk Java API, file format specifications,
  and samtools/bcftools source code.
baseurl: "/hts-specs"
url: "http://samtools.github.io"
github_username: samtools
exclude: ["*.tex", diff, img, MAINTAINERS.md, Makefile, new, README.md, scripts, test]

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true
  toc_levels: 1..3
